config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :snaps do
    resources :comments
    member do
      get :like
    end
  end

  root 'snaps#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :snap

  validates :content, length: {minimum: 3, maximum: 300}
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :notified_by, class_name: "User"
  belongs_to :snap

  validates :user_id, :notified_by_id, :snap_id, :notice_type, presence: true

  def read?
    read
  end

  def unread?
    !read
  end
end

app/models/snap.rb
class Snap < ActiveRecord::Base
  has_attached_file :image, styles: {large: "640x", medium: "300x300", thumb: "100x100"}, default_ur: "/images/:style/missing.png"

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  accepts_nested_attributes_for :comments

  validates :user_id, presence: true
  validates_attachment :image, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :snaps, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :username, presence: true, length: {maximum: 25}

  acts_as_voter

  def has_unread_notifications?
    puts "\n\n#{notifications.inspect}\n\n"
    notifications.any?{|n| n.unread?}
  end

  def unread_notifications
    notifications.where(read: false)
  end

  def recent_unread_notifications
    notifications.where(read: false).order(created_at: :desc).last(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_snap

  def create
    @comment = @snap.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      create_notification @snap
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end  
    else
      flash[:alert] = "Hmm, comment refused"
      render root_path
    end
  end

  def destroy
    @comment = @snap.comments.find(params[:id])
    if @comment.destroy
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_snap
    @snap = Snap.find(params[:snap_id])
  end

  def create_notification(snap)
    return if snap.user.id == current_user.id
    puts "here"
    n=Notification.create(
      user_id: snap.user.id,
      snap_id: snap.id,
      notified_by_id: current_user.id,
      notice_type: 'comment',
      read: false
    )
    puts "\n\n#{n.errors.full_messages}\n\n"
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.notifications.order(created_at: :desc)  
  end

  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to snap_path(@notification.snap)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :current_password)
  end
end

app/controllers/snaps_controller.rb
class SnapsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_snap, only: [:show, :edit, :update, :destroy, :like]
  before_action :owned_snap, only: [:edit, :update, :destroy]

  def index
    @snaps = Snap.all
  end

  def show
  end

  def new
    @snap = current_user.snaps.build
  end

  def create
    @snap = current_user.snaps.build(snap_params)
    if @snap.save
      flash[:success] = "Your snap has been uploaded"
      redirect_to snaps_path
    else
      flash[:alert] = "Please correct the following errors"
      render :new
    end
  end

  def edit
  end

  def update
    if @snap.update(snap_params)
      flash[:success] = "Your snap has been updated"
      redirect_to snap_path(@snap)
    else
      flash[:alert] = "Please correct the following errors"
      render :edit
    end
  end

  def destroy
    @snap.destroy
    redirect_to root_path
  end

  def like
    if current_user.voted_up_on? @snap
      flash[:alert] = "You can only like a snap once."
    elsif current_user == @snap.user
      flash[:alert] = "You can't like your own snap. Harsh, I know."
    else
      @snap.liked_by(current_user)
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end  
    end
  end

  private
  def snap_params
    params.require(:snap).permit(:caption, :image, :user_id)
  end

  def set_snap
    @snap = Snap.find(params[:id])
  end

  def owned_snap
    unless current_user == @snap.user
      flash[:alert] = "You can only update your own snaps!"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def form_image_select(snap)
    return image_tag snap.image.url(:medium), 
      id: 'image-preview',
      class: 'img-responsive' if snap.image.exists?
    image_tag 'placeholder.png', id: 'image-preview', class: 'img-responsive'
  end

  def read_class(n)
    n.read? ? "read" : ""
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/snaps_helper.rb
module SnapsHelper
  def liked_snap(snap)
    current_user.voted_for?(snap) ? "heart" : "heart-empty"
  end
end

app/views/comments/_comment.html.haml
#comment
  .user-name
    = comment.user.username
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to snap_comment_path(snap, comment), method: :delete, data: { confirm: "Are you sure?"}, remote: true do
      %span(class="glyphicon glyphicon-remove delete-comment")

app/views/comments/create.js.erb
$('#comments_<%= @snap.id %>').append("<%= j render 'comments/comment', snap: @snap, comment: @comment %>");
$('#comment_content_<%= @snap.id %>').val('');

app/views/comments/destroy.js.erb
$('#comments_<%= @snap.id %>').html("<%= j render @snap.comments, snap: @snap, comment: @comment %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snapagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navbar' %>
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/notifications/_notification.html.haml
%li
  = link_to "#{notification.notified_by.username} has #{notification.notice_type}ed your snap",
    link_through_path(notification)

app/views/notifications/_notification_dropdown.html.haml
.dropdown.notification-dropdown
  %button.btn.btn-default.dropdown-toggle{type: 'button', id: 'dropdownMenu1', data: {toggle: 'dropdown'}, 'aria-haspopup' => true, 'aria-expanded' => true }
    = user.unread_notifications.count
    %span(class="glyphicon glyphicon-flag")
  %ul.dropdown-menu{'aria-labelledby' => 'dropdownMenu1'}
    %li.dropdown-header.text-center Notifications
    - user.recent_unread_notifications.each do |n|
      = render 'notifications/notification', notification: n
    %li.divider{role: 'separator'}
      %li.text-center= link_to 'View All', notifications_path

app/views/notifications/link_through.html.haml
%h1 Notifications#link_through
%p Find me in app/views/notifications/link_through.html.haml

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bsnavbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "Snapagram", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = render 'notifications/notification_dropdown', user: current_user
          %li= link_to "New Snap", new_snap_path
          %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Login", new_user_session_path
          %li= link_to "Register", new_user_registration_path

app/views/snaps/_form.html.haml
.snaps-wrapper
  .snap
    .snap-body
      .image-wrap
        = form_image_select(@snap)
        = simple_form_for @snap, html: { multipart: true} do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)'}
            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add a caption'
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/snaps/_snap.html.haml
.snaps-wrapper
  .snap
    .snap-head
      .thumb-img
      .user-name=snap.user.username
      .time-ago
        ="#{time_ago_in_words snap.created_at} ago"
    .image.center-block
      =link_to image_tag(snap.image.url(:medium), class: 'img-responsive'), snap_path(snap)
    .snap-bottom
      .caption
        .caption-content=snap.caption
        .comments{id: "comments_#{snap.id}"}
        - if snap.comments
          - snap.comments.each do |comment|
            = render "comments/comment", snap: snap, comment: comment

    .comment-like-form.row
      .col-sm-1
        = link_to '', like_snap_path(snap.id), remote: true, id: "like_#{snap.id}", class: "glyphicon glyphicon-#{liked_snap(snap)}"
        %span.likes-count
          = snap.get_likes.count
      .comment-form.co-sm-11
        = form_for [snap, snap.comments.build], remote: true do |f|
          = f.text_field :content, placeholder: "Add a comment ...", class: "comment_content", id: "comment_content_#{snap.id}"

app/views/snaps/edit.haml
= render "form"
.text-center.edit-links
  = link_to "Delete", snap_path(@snap), method: :delete
  | 
  = link_to 'Cancel', snaps_path

app/views/snaps/index.html.haml
.snaps-wrapper.row
  - @snaps.each do |snap|
    = render 'snap', snap: snap

app/views/snaps/like.js.erb
$("#like_<%= @snap.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#like_<%= @snap.id %>").next().text("<%= @snap.get_likes.count %>");

app/views/snaps/new.html.haml
=render "form"

app/views/snaps/show.html.haml
= render 'snap', snap: @snap
.text-center.edit-links
  = link_to 'Cancel', snaps_path
  - if @snap.user_id == current_user.id
    |
    = link_to "Edit", edit_snap_path(@snap)